name: skelter
description: >
  A production-grade Flutter boilerplate by SolGuruz, designed to jump-start
  app development with prebuilt utility functions, reusable UI components,
  state management, test-ready setup, and a clean scalable architecture.

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: 10.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_core: ^4.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  intl_phone_number_input: ^0.7.4
  phone_numbers_parser: ^9.0.3
  pinput: ^5.0.0
  sms_autofill: ^2.4.0
  equatable: ^2.0.5
  flutter_tabler_icons: ^1.43.0
  flutter_localization: ^0.3.2
  flutter_svg: ^2.1.0
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.8.0
  debounce_throttle: ^2.0.0
  flutter_fgbg: ^0.7.1
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  country_picker: ^2.0.27
  shared_preferences: ^2.5.3
  sizer: ^3.0.5
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  mobkit_dashed_border: ^0.0.8
  shimmer: ^3.0.0
  image_viewer_pro: ^1.0.0
  easy_stepper: ^0.8.5+1
  flutter_rating_bar_plus: ^4.0.2
  file_picker: 8.3.3
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.6
  speech_to_text: 7.0.0
  avatar_glow: ^3.0.1
  permission_handler: 12.0.0+1
  url_launcher: ^6.3.2
  firebase_remote_config: ^6.0.0
  package_info_plus: ^8.3.0
  dartz: ^0.10.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  lottie: ^3.3.1
  http_certificate_pinning: ^3.0.1
  flutter_secure_storage: ^9.2.4
  dio_cache_interceptor: ^4.0.3
  http_cache_file_store: ^2.0.1
  google_nav_bar: ^5.0.7
  clarity_flutter: ^1.4.0
  mime: ^2.0.0
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.2
  flutter_gen_runner: ^5.8.0
  auto_route_generator: ^10.2.3
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  alchemist: ^0.12.1
  mocktail_image_network: ^1.2.0
  patrol: ^3.19.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/sg_skelter_logo.png

  android_12:
    image: assets/images/sg_skelter_logo.png
    icon_background_color: "#ffffff"
    android_gravity: center

flutter:
  uses-material-design: true
  # TODO: https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/test/images/
    - assets/test/files/
    - .env
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        # 200 ExtraLight
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 200

        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 200

        #300 Light
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 300

        #400 Normal
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 400

        #500 Medium
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 500

        #600 Semi-bold
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 600

patrol:
  app_name: Flutter Skelter
  flavors: dev
  android:
    package_name: com.solguruz.skelter.dev
  ios:
    bundle_id: com.solguruz.skelter.dev
